apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"ebs-sc"},"provisioner":"ebs.csi.aws.com","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-10-13T16:10:22Z"
  name: ebs-sc-immediate
  resourceVersion: "4189"
  uid: ca986ec2-7c7b-42fc-9ab0-634326f542dc
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate  # Changed to Immediate

